baseURL = "https://redoste.xyz/"
languageCode = "en-us"
title = "redoste"
theme = "bare-html-dark"
copyright = "Â© 2020 - 2026 redoste - [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/)"
enableRobotsTXT = true

[params]
	dateFormat = "2006-01-02 15:04 -0700"

[outputs]
	home = ["HTML"]
	page = ["HTML"]
	taxonomy = ["HTML"]
	taxonomyTerm = ["HTML"]
	section = ["HTML", "RSS"]

[permalinks]
	posts = "/:year/:month/:day/:title/"

[menu]
	[[menu.main]]
		name = "RSS"
		url = "/posts/index.xml"
	[[menu.main]]
		name = "Projects"
		url = "/projects/"
	[[menu.main]]
		name = "About"
		url = "/about/"
